models/Markets.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Query;
use yii\rbac\Item;

/**
 * This is the model class for table "markets".
 *
 * @property string $market_id
 * @property string $market_name
 * @property string $market_address
 * @property string $market_contacts
 * @property string $created_at
 * @property string $modified_at
 * @property integer $active_status
 *
 * @property FoodstuffMarkets[] $foodstuffMarkets
 */
class Markets extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'markets';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' =>[
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'modified_at'],
                    ActiveRecord::EVENT_AFTER_UPDATE => ['modified_at'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['market_name', 'market_address', 'market_contacts'], 'required'],
            [['market_name', 'market_address', 'market_contacts'], 'string'],
            [['created_at', 'modified_at'], 'safe'],
            [['active_status'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'market_id' => 'Market ID',
            'market_name' => 'Name',
            'market_address' => 'Address',
            'market_contacts' => 'Contacts',
            'created_at' => 'Created At',
            'modified_at' => 'Modified At',
            'active_status' => 'Active Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFoodstuffMarkets()
    {
        return $this->hasMany(FoodstuffMarkets::className(), ['market_id' => 'market_id']);
    }

    /**
     * @return \yii\db\ActiveRecord
     */
    public function getFoodstuff()
    {
        return $this->hasMany(Foodstuffs::className(), ['market_id' => 'foodstuff_id'])
            ->viaTable('foodstuff_markets', ['market_id', 'market_id']);
    }

    public static function getValidCategories($marketId)
    {
        return (new Query())
            ->distinct(true)
            ->select(['categories.*'])
            ->from('foodstuff_markets, foodstuffs, markets, categories')
            ->where('foodstuff_markets.foodstuff_id = foodstuffs.foodstuff_id')
            ->andWhere('foodstuff_markets.market_id = markets.market_id')
            ->andWhere(['foodstuff_markets.market_id' => $marketId])
            ->andWhere('categories.category_id = foodstuffs.category_id')
            ->all();
    }

    public static function getMarketByCategoryId($marketId, $categoryId)
    {
        return (new Query())
            ->select(['foodstuff_markets.*', 'foodstuffs.*', 'markets.*', 'measures.*', 'categories.*'])
            ->from('foodstuff_markets, foodstuffs, markets, measures, categories')
            ->where('foodstuff_markets.foodstuff_id = foodstuffs.foodstuff_id')
            ->andWhere('foodstuff_markets.market_id = markets.market_id')
            ->andWhere(['foodstuff_markets.market_id' => $marketId])
            ->andWhere('measures.measure_id=foodstuff_markets.foodstuff_market_price_measure_id')
            ->andWhere('categories.category_id = foodstuffs.category_id')
            ->andWhere(['foodstuffs.category_id' => $categoryId])
            ->all();
    }
}

controllers/MarketController.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/20/15
 * Time: 10:33 PM
 */

namespace app\controllers;


use app\models\Categories;
use app\models\Markets;
use yii\db\Query;
use yii\web\Controller;

class MarketController extends Controller{

    public function actionIndex($id = null, $cat_id = null){

        if ($id != null){
            $firstMarketId = $id;
        }
        else{
            $markets = Markets::find()->limit(1)->one();
            $firstMarketId = $markets->market_id;
        }

        $market = (new Markets())->findOne($firstMarketId);

        $categories = Markets::getValidCategories($firstMarketId);

        if ($cat_id != null){
            $categoryId = $cat_id;
        }
        else{
            $categoryId = $categories[0]["category_id"];
        }

        $selectedCategory = (new Categories())->findOne($categoryId);

        $model = Markets::getMarketByCategoryId($firstMarketId, $categoryId);

        $allMarkets = Markets::find()->all();

        return $this->render('index', ['categories' => $categories, 'model' => $model, 'selectedCategory' => $selectedCategory, 'market' => $market, 'allMarkets' => $allMarkets]);
    }
}

controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/19/15
 * Time: 8:30 PM
 */

namespace app\controllers;


use app\models\Categories;
use app\models\FoodstuffMarkets;
use app\models\Foodstuffs;
use yii\data\Pagination;
use yii\db\Query;
use yii\web\Controller;

class ProductController extends Controller{

    public function actionIndex(){
        $categories = (new Categories())->find()->all();
        return $this->render('index', ['categories' => $categories]);
    }

    public function actionCategory($id){
        $categories = (new Categories())->find()->all();
        $selectedCategory = (new Categories())->findOne($id);
        return $this->render('index', ['categories' => $categories,'selectedCategory' => $selectedCategory]);
    }

    public function actionPrices($cat_id, $prod_id){
        $query = FoodstuffMarkets::getFoodstuffPrices(intval($prod_id));

        $others = (new Foodstuffs())->find()->where(['category_id' => $cat_id])->all();

        return $this->render('prices', ['model' => $query, 'others' => $others]);
    }

    /**
     * @param $food_market_id
     * @return string
     */
    public function actionItem($food_market_id){

        $foodstuffMarket = (new FoodstuffMarkets())->findOne($food_market_id);

        $foodstuff = $foodstuffMarket->getFoodstuff()->limit(1)->one();
        $selectedMarket = $foodstuffMarket->getMarket()->limit(1)->one();
        $measure = $foodstuffMarket->getFoodstuffMarketPriceMeasure()->limit(1)->one();

        $markets = FoodstuffMarkets::getSpecificSuppliers($foodstuff->foodstuff_id);

        $table_data = FoodstuffMarkets::getFoodstuffPriceCompare($foodstuff->foodstuff_id);


        return $this->render('item', ['markets' => $markets, 'tableData' => $table_data, 'selectedMarket' => $selectedMarket, 'foodstuff' => $foodstuff, 'foodstuffMarket' => $foodstuffMarket, 'measure' => $measure]);
    }
}

views/market/index.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/20/15
 * Time: 10:35 PM
 *
 * @var $model mixed
 * @var $categories mixed
 * @var $selectedCategory \app\models\Categories
 * @var $market \app\models\Markets
 * @var $allMarkets \app\models\Markets []
 */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Oraih';
$this->params['breadcrumbs'][] = $this->title;
$row_begin = '<div class="row mt-20">';
$row_end = '</div>';
$size = count($model);
?>

<div class="container mt">
      <div class="row">
        <!-- SIDEBAR -->
        <!--===============================================================-->
        <div class="col-md-3">
          <div class="row-heading">
            <div class="col-sm-12">
              <h3 class="title-sm hr-left text-uppercase">Foodstuff Categories</h3>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">

                    <div class="list-group">

                        <?php foreach($categories as $category): ?>
                            <a href="<?= Url::to(['market/index', 'id' => $market->market_id, 'cat_id' => $category["category_id"]])?>" class="<?= 'list-group-item' . (($category["category_id"] == $selectedCategory->category_id) ? ' active' : '') ?>">
                                <?= Html::encode($category["category_name"])?>
                            </a>
                        <?php endforeach ?>

                    </div>
                </div>
            </div>
          </div>
          <div class="row-heading">
            <div class="col-sm-12">
              <h3 class="title-sm hr-left text-uppercase">Details</h3>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="icon-box bordered">
                <i class="fa fa-home fa-3x text-theme"></i>
                <h3 class="title-sm text-theme">Point of Sales</h3>
                <p class="text-theme"><?= Html::encode($market->market_address) ?></p>
              </div>
            </div>
          </div>
            <br>
            <div class="row">
                <div class="col-sm-12">
                    <div class="icon-box bordered">
                        <i class="fa fa-bullhorn fa-3x text-theme"></i>
                        <h3 class="title-sm text-theme">Contact</h3>
                        <p class="text-theme"><?= Html::encode($market->market_contacts) ?></p>
                    </div>
                </div>
            </div>
            <div class="row-heading">
                <div class="col-sm-12">
                    <h3 class="title-sm hr-left text-uppercase">Other Markets</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">

                        <div class="list-group">

                            <?php foreach($allMarkets as $mart): ?>
                                <a href="<?= Url::to(['market/index', 'id' => $mart->market_id])?>" class="<?= 'list-group-item' . (($mart->market_id == $market->market_id) ? ' active' : '') ?>">
                                    <?= Html::encode($mart->market_name)?>
                                </a>
                            <?php endforeach ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- MAIN CONTENT -->
        <!--===============================================================-->
        <div class="col-md-9">
            <h2 class="title-v2"><b><?= Html::encode($market->market_name) ?> </b>- <?= Html::encode($selectedCategory->category_name)?></h2>

            <?php
            for($i = 0; $i < $size; $i++){
                $item = $model[$i];

                if (($i != 0 && $i % 4 == 0)){
                    echo($row_end);
                }

                if ($i == 0 || $i % 4 == 0){
                    echo($row_begin);
                }

                $img_url = ($item['foodstuff_image_url'] == "") ? 'z_theme/assets/images/shop/500x500.gif' : ('uploads/' . $item["foodstuff_image_url"]);

                echo('<div class="col-md-4">
                    <div class="shop-box bordered">
                        <a href="#" class="img-box text-theme">
                            <img class="img-responsive" src="' . Yii::$app->urlManager->createAbsoluteUrl($img_url) .'" alt="img-theme">
                        </a>
                        <h3 class="title-sm text-theme text-theme-sm"><a href="#">' . $item["foodstuff_name"] . '</a></h3>
                        <p class="text-theme-sm"><small>' . $item["foodstuff_desc"] . '</small>
                        </p>
                        <h3 class="shop-price text-theme-sm"> &#8358;' . $item["foodstuff_market_price"] . ' / ' . $item["measure_name"] .'</h3>
                        <a class="btn btn-primary btn-tiny btn-sm text-theme-sm" href="' . Url::to(["product/item", "food_market_id" => $item["foodstuff_market_id"]]) . '"><i class="fa fa-angle-right"></i>Details</a>
                    </div>
                </div>');

                if ($i == $size - 1){
                    echo($row_end);
                }
            }
            ?>


        </div>
      </div>
</div>